language: python
python:
  - "3.5"
services:
  - mysql

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  - pip install coverage coveralls mock
before_script:
  - cp conf/test.conf ../django.conf
script:
  - python ./manage.py test
  - coverage run manage.py test
after_success:
  - coverage report
  - coveralls