# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170213_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='', max_length=255, verbose_name='message subject'),
        ),
    ]
