# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170224_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembership',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='chat inviter'),
        ),
    ]
