# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ugc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends2', to=settings.AUTH_USER_MODEL, verbose_name='friend')),
            ],
        ),
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('dated_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ugc.Dated')),
                ('approved', models.BooleanField(verbose_name='is approved')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_applications', to=settings.AUTH_USER_MODEL, verbose_name='user responded request')),
            ],
            options={
                'abstract': False,
            },
            bases=('ugc.dated', models.Model),
        ),
        migrations.AddField(
            model_name='friends',
            name='friendShip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendship.FriendShip', verbose_name='friendship'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
