# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends2', to=settings.AUTH_USER_MODEL, verbose_name='friend')),
            ],
        ),
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='creating time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updating time')),
                ('approved', models.BooleanField(verbose_name='is approved')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_applications', to=settings.AUTH_USER_MODEL, verbose_name='user responded request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='friends',
            name='friendShip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendship.FriendShip', verbose_name='friendship'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
