# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_auto_20170214_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='is approved'),
        ),
    ]
