# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_popularuser'),
        ('ugc', '0002_auto_20170224_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAward',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('awards.baseaward',),
        ),
    ]
