# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('award_name', models.CharField(max_length=255)),
                ('award_description', models.TextField()),
                ('users', models.ManyToManyField(related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'awards',
            },
        ),
    ]
